kind: pipeline
name: default
type: docker

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
- name: package image
  image: plugins/docker
  settings:
    username: caoxiaozh@163.com
    password: cxzcxz123
    repo: hardycao/repo1
    registry: registry.cn-beijing.aliyuncs.com
    # mirror: https://7bxty0zf.mirror.aliyuncs.com
    target: staging
    tags: "1.0"